name: Small test case
description: Small Test case against the OSPO REST API
author: 'Bill Wagner'
branding:
  icon: refresh-cw
  color: purple

runs:
  using: docker
  image: ../../smalltest.Dockerfile
