using System.CommandLine;
using XmlDocConflictResolver;

class Program
{
    static async Task<int> Main(string[] args)
    {
        var ixmlOption = new Option<DirectoryInfo?>(
            name: "--ixml",
            description: "The path to the IntelliSense XML files generated by the compiler.")
        { IsRequired = true };

        var ecmaxmlOption = new Option<DirectoryInfo?>(
            name: "--ecmaxml",
            description: "The path to the ECMAXML files from the docs repo.")
        { IsRequired = true };

        var rootCommand = new RootCommand("IntelliSense XML <-> ECMAXML doc comment resolver app");
        rootCommand.AddOption(ixmlOption);
        rootCommand.AddOption(ecmaxmlOption);

        rootCommand.SetHandler((ixmlDir, ecmaxmlDir) =>
        {
            MergeAndAnnotate(ixmlDir!, ecmaxmlDir!);
        },
            ixmlOption, ecmaxmlOption);

        return await rootCommand.InvokeAsync(args);
    }

    static void MergeAndAnnotate(DirectoryInfo iXmlDir, DirectoryInfo ecmaxmlDir)
    {
        // Load all files
        // For each member in the IntelliSense XML, see if there's non-emtpy text in ECMAXML.
        // If so, save both versions of the text in the IntelliSense XML object.
        // After the for each loop, write new XML for any namespaces
        // that have members with more than one copy of summary/returns/param etc.

        var checker = new ConflictChecker(iXmlDir, ecmaxmlDir);
        checker.CollectFiles();
        checker.Start();
        checker.SaveToDisk();
        checker.AddConflictMarkers();
        checker.CleanUpFiles();
    }
}