name: 'What''s new in docs'
description: 'Automatically generate a PR that adds a "what''s new in docs" file for the recent time period.'
author: Bill Wagner
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'zap'
  color: 'purple'
inputs:
  owner:
    description: 'The GitHub organization name.'
    required: true
  repo:
    description: 'The GitHub repository name within the provided organization.'
    required: true
  branch:
    description: 'The branch name within the provided repository.'
    default: main
  docset:
    description: 'The product name within the provided repository.'
    default: 'false'
  startdate:
    description: 'A range start date in a valid format.'
  enddate:
    description: 'A range end date in a valid format.'
  savedir:
    description: 'A directory path to which the generated Markdown file should be written.'
    required: true
  reporoot:
    description: 'The path to the repository root folder.'
runs:
  using: docker
  image: ../whatsnew.Dockerfile
  args:
    - '--owner'
    - ${{ inputs.owner }}
    - '--repo'
    - ${{ inputs.repo }}
    - '--branch'
    - ${{ inputs.branch }}
    - '--docset'
    - ${{ inputs.docset }}
    - '--startdate'
    - ${{ inputs.startdate }}
    - '--enddate'
    - ${{ inputs.enddate }}
    - '--savedir'
    - ${{ inputs.savedir }}
    - '--reporoot'
    - ${{ inputs.reporoot }} 
