name: 'Status check checker'
description: "Checks the OpenPublishing.Build status to see if there are build warnings or failures."
author: 'Genevieve Warren'
inputs:
  repo_token:
    description: 'The GITHUB_TOKEN secret. Requires the following permissions: statuses: write.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
