name: 'Preview link generator'
description: 'Waits for OpenPublishing.Build to complete, then extracts preview links from the OPS build report and updates the pull request body.'
author: 'Genevieve Warren'
inputs:
  repo_token:
    description: 'The GITHUB_TOKEN secret. Requires the following permissions: pull-requests: write.'
    required: true
  collapsible_after:
    description: 'The number at which the automated preview table defaults as collapsed but expandable, using the HTML summary and details elements.'
    default: '10'
  max_row_count:
    description: 'The maximum number of rows to display in the automated preview table.'
    default: '30'
runs:
  using: 'node16'
  main: 'dist/index.js'
